# app/graph/state.py
from typing import Annotated, Optional, Sequence, List, Dict, Any
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    # add_messages automatically appends new messages to the existing sequence
    messages: Annotated[Sequence[BaseMessage], add_messages]
    user_id: Optional[str]
    session_id: Optional[str]
    # ─── PHASE 1: GUARDRAIL & INTENT CLASSIFICATION ───
    is_in_domain: Optional[bool]     # True if travel related, False otherwise
    intent_category: Optional[str]   # 'hotel_booking', 'travel_faq', 'itinerary_planning', 'ambiguous'
    complexity: Optional[str]        # Complexity tier assigned by Supervisor: 'low', 'medium', 'high'
    objective: Optional[str]         # General objective of the user prompt
    detected_language: Optional[str] # Language of the user prompt
    intent_confidence: Optional[float] # Confidence score 0.0-1.0
    ambiguity_reason: Optional[str]    # Explanation if intent is ambiguous

    # ─── COST TRACKING ───
    tier1_input_tokens: Optional[int]
    tier1_output_tokens: Optional[int]
    tier2_input_tokens: Optional[int]
    tier2_output_tokens: Optional[int]
    estimated_cost_usd: Optional[float]

    # ─── PHASE 2: WORKFLOW MEMORY (PROCEDURAL STATE) ───
    # Keeps track of the execution plan generated by the Planner Node
    # Example: [{"id": 1, "desc": "Find hotel", "status": "pending", "result": "raw output", "findings": [...]}]
    tasks: List[Dict[str, Any]]
    current_task_id: Optional[int]
    
    # ─── PHASE 2: LOOP MANAGEMENT & SAFEGUARDS ───
    iteration_count: int         # Tracks graph cycles to enforce Max Iterations
    tool_call_count: int         # Tracks total tools invoked to enforce Budget Limits
    action_history: List[str]    # Records hashed tool calls to prevent Duplicate Actions
    rework_count: int            # Tracks Critic→Reflection rework cycles to enforce Max Rework

    # ─── EVALUATION MEMORY ───
    evaluator_feedback: Optional[str]
    evaluator_notes: Optional[str]
    needs_rework: Optional[bool]
    fact_check_result: Optional[Dict[str, Any]]
    final_answer: Optional[str]

    # ─── CONTENT/EXTRACTION PIPELINE STATE ───
    # Set by node_finding_extractor after each executor run.
    # Decouples task_manager from fragile JSON parsing of executor message content.
    raw_executor_output: Optional[str]      # Plain-text result summary extracted from executor output
    extracted_findings: List[Dict[str, Any]] # Structured List[Finding] dicts from the extractor

    # ─── CACHING ───
    cache_hit: Optional[bool]